package cmd

import "testing"

// TestBeadIDPattern pins the regex used by `gt polecat checkout-branch` to
// validate the bead-id arg before constructing the branch name. The pattern
// has to accept the standard bd issue forms (gt-mwy, gt-mwy.5, hq-1pl,
// gt-i71) without admitting shell-injection-friendly characters that would
// then leak into the branch name.
func TestBeadIDPattern(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		// Positives — every shape we see in practice.
		{"gt-mwy", true},
		{"gt-mwy.5", true},
		{"gt-i71", true},
		{"hq-1pl", true},
		{"hq-wisp-ku6", true},
		{"gt-1qlg", true},
		// Subtask depth more than one level (gt-mwy.5.2) is occasionally
		// generated by mayor when fanning out work; the pattern must accept
		// chained .N suffixes without degenerating to "anything goes".
		{"gt-mwy.5.2", true},

		// Negatives — guard against shell-injection / branch-name pollution.
		{"", false},
		{"gt", false},                 // no suffix
		{"gt-", false},                // empty suffix
		{"GT-MWY", false},             // uppercase prefix
		{"gt-MWY", false},             // uppercase body
		{"gt mwy", false},             // space
		{"gt-mwy/something", false},   // slash
		{"gt-mwy;rm -rf /", false},    // shell metacharacter
		{"gt-mwy`whoami`", false},     // backticks
		{"gt-mwy$(whoami)", false},    // command substitution
		{"a-mwy", false},              // 1-char prefix
		{"abcd-mwy", false},           // 4-char prefix (we cap at 3)
		{"--gt-mwy", false},           // leading dashes
	}
	for _, c := range cases {
		t.Run(c.in, func(t *testing.T) {
			got := beadIDPattern.MatchString(c.in)
			if got != c.want {
				t.Errorf("beadIDPattern.MatchString(%q) = %v; want %v", c.in, got, c.want)
			}
		})
	}
}
