package cmd

import (
	"strings"
	"testing"

	"github.com/steveyegge/gastown/internal/beads"
	"github.com/steveyegge/gastown/internal/refinery"
)

// TestExtractDescField pins the small parser used to read review_pr off the
// MR bead description. review_pr is now a first-class MRField (gt-5le:
// written by `gt refinery pr create`), but the dispatch subcommand still
// reads it directly to keep the first-match-wins guard below. The parser
// must:
//   - find the first occurrence of `key:` (subsequent prose references to
//     the same key must NOT shadow the structured value)
//   - tolerate leading whitespace on the line (a bd description rendered
//     with indented prose blocks would otherwise miss the field)
//   - return empty string when the key is absent
func TestExtractDescField(t *testing.T) {
	cases := []struct {
		name string
		desc string
		key  string
		want string
	}{
		{"key not present", "branch: foo\n", "review_pr", ""},
		{"present at start", "review_pr: 42\nbranch: x\n", "review_pr", "42"},
		{"present mid-block", "branch: x\nreview_pr: 42\n", "review_pr", "42"},
		{"indented line tolerated", "  review_pr: 42\n", "review_pr", "42"},
		{"first wins over later prose mention", "review_pr: 42\nbranch: x\n\nlater: review_pr: 99 typo\n", "review_pr", "42"},
		{"empty value", "review_pr:\n", "review_pr", ""},
		{"value with surrounding whitespace", "review_pr:    42   \n", "review_pr", "42"},
		{"empty description", "", "review_pr", ""},
		{"key not present, prose mentions it", "Notes: see review_pr in the bead\n", "review_pr", ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := extractDescField(c.desc, c.key)
			if got != c.want {
				t.Errorf("extractDescField(%q, %q) = %q; want %q", c.desc, c.key, got, c.want)
			}
		})
	}
}

// TestBuildReviewFixMission pins the polecat-mission text generated by the
// dispatch subcommand. The mission must encode every behavioural invariant
// the formula's prose blob used to enforce, in numbered-step form so the
// LLM polecat can't blur the contract.
func TestBuildReviewFixMission(t *testing.T) {
	threadsJSON := `[{"id":"PRRT_xyz","author":"augmentcode","path":"a.go","line":42,"body":"fix"}]`
	mission := buildReviewFixMission(123, threadsJSON, "augmentcode")

	// Every invariant must be present in the rendered mission.
	requiredFragments := []struct {
		name string
		want string
	}{
		// G33: imperative branch-entry via the just-shipped subcommand.
		{"checkout-branch step 1", "gt polecat checkout-branch"},
		// G14: thread JSON enumerated verbatim, not paraphrased.
		{"threads JSON inline", threadsJSON},
		// G13: reply-AND-resolve, not reply-only.
		{"reply-and-resolve", "Resolve every thread"},
		{"resolve via gh api", "resolveReviewThread"},
		// G12b: author-agnostic.
		{"author-agnostic guidance", "regardless of opener"},
		// G36: gt done updates commit_sha (handles bead refresh).
		{"gt done completion", "gt done"},
		// PR number rendered.
		{"PR number rendered", "PR #123"},
		// Reviewer name rendered when supplied.
		{"reviewer name rendered", "augmentcode"},
	}
	for _, rf := range requiredFragments {
		t.Run(rf.name, func(t *testing.T) {
			if !strings.Contains(mission, rf.want) {
				t.Errorf("mission missing %q: got %q", rf.want, mission)
			}
		})
	}

	// Ensure mission text is imperative-steps-first (numbered list) rather
	// than narrative — the original formula prose was the failure mode this
	// fix exists to close.
	for _, step := range []string{"1.", "2.", "3.", "4.", "5.", "6.", "7."} {
		if !strings.Contains(mission, step) {
			t.Errorf("mission missing step %q (must be numbered for LLM clarity): %s", step, mission)
		}
	}
}

// Empty reviewer name shouldn't render an empty parenthetical
// — the mission falls back to "the configured pr_reviewer" wording.
func TestBuildReviewFixMission_EmptyReviewer_RendersFallback(t *testing.T) {
	mission := buildReviewFixMission(7, "[]", "")
	if strings.Contains(mission, "wake (the configured pr_reviewer)") {
		t.Errorf("empty reviewer must not produce empty parenthetical, got: %s", mission)
	}
	if !strings.Contains(mission, "the configured pr_reviewer") {
		t.Errorf("empty reviewer must fall back to generic 'the configured pr_reviewer' phrasing, got: %s", mission)
	}
}

// TestReviewFixSlingArgs pins the gt sling command shape for review-fix
// dispatch. The regression that killed the whole review-fix loop (gt-o4z /
// hq-eew) lived entirely in these arguments: the dispatch shelled out to
// `gt sling review-fix/<id> <rig> ... --json`, but gt sling has no
// `review-fix/<id>` target form and no --json flag, so cobra rejected the
// unknown flag, printed its usage banner, and exited 1. These assertions fail
// if either mistake is reintroduced.
func TestReviewFixSlingArgs(t *testing.T) {
	state := dispatchReviewFixState{
		PRNumber:    42,
		Branch:      "polecat/furiosa-gt-abc",
		SourceIssue: "gt-abc",
	}
	// Open-source path: dispatchBeadID is the source issue itself.
	args := reviewFixSlingArgs("gastown", state.SourceIssue, state, "mission text")

	if len(args) == 0 || args[0] != "sling" {
		t.Fatalf("args[0] must be \"sling\", got %v", args)
	}
	// Positional bead arg must be the bare source issue — NOT the old
	// review-fix/<id> pseudo-target that gt sling could never resolve.
	if args[1] != "gt-abc" {
		t.Errorf("bead arg = %q; want bare source issue \"gt-abc\" (no review-fix/ prefix)", args[1])
	}
	if args[2] != "gastown" {
		t.Errorf("target arg = %q; want rig \"gastown\"", args[2])
	}

	joined := strings.Join(args, " ")
	for _, frag := range []string{"review-fix/", "--json"} {
		if strings.Contains(joined, frag) {
			t.Errorf("args must not contain %q (gt sling rejects it): %v", frag, args)
		}
	}

	// Required flags for the dispatch to land a polecat on the PR branch.
	want := map[string]string{
		"--review-pr":     "42",
		"--review-branch": "polecat/furiosa-gt-abc",
		"--args":          "mission text",
	}
	for flag, val := range want {
		idx := argIndexOf(args, flag)
		if idx < 0 {
			t.Errorf("missing flag %q in %v", flag, args)
			continue
		}
		if idx+1 >= len(args) || args[idx+1] != val {
			t.Errorf("flag %q value = %q; want %q", flag, valueAt(args, idx+1), val)
		}
	}
	if argIndexOf(args, "--force") < 0 {
		t.Errorf("missing --force (source issue is still hooked to the terminal initial polecat): %v", args)
	}
}

// TestReviewFixSlingArgs_FreshBead verifies that when a fresh dispatch bead is
// used (closed-source path), reviewFixSlingArgs substitutes the fresh bead ID
// for the source issue in the positional arg while keeping all other flags.
func TestReviewFixSlingArgs_FreshBead(t *testing.T) {
	state := dispatchReviewFixState{
		PRNumber:    103,
		Branch:      "polecat/furiosa/gt-dws@abc123",
		SourceIssue: "gt-dws", // the closed source bead
	}
	freshBeadID := "gt-cpb" // the fresh review-fix bead created for closed-source path
	args := reviewFixSlingArgs("gastown", freshBeadID, state, "mission text")

	if args[0] != "sling" {
		t.Fatalf("args[0] must be \"sling\", got %v", args)
	}
	// Fresh bead ID, not the closed source issue, must be the sling target.
	if args[1] != freshBeadID {
		t.Errorf("bead arg = %q; want fresh bead %q (closed source %q must not appear here)", args[1], freshBeadID, state.SourceIssue)
	}
	if args[2] != "gastown" {
		t.Errorf("target arg = %q; want rig \"gastown\"", args[2])
	}
	// PR branch routing flags must still be present.
	for flag, val := range map[string]string{
		"--review-pr":     "103",
		"--review-branch": "polecat/furiosa/gt-dws@abc123",
	} {
		idx := argIndexOf(args, flag)
		if idx < 0 {
			t.Errorf("missing flag %q in fresh-bead args %v", flag, args)
			continue
		}
		if idx+1 >= len(args) || args[idx+1] != val {
			t.Errorf("flag %q value = %q; want %q", flag, valueAt(args, idx+1), val)
		}
	}
	if argIndexOf(args, "--force") < 0 {
		t.Errorf("missing --force in fresh-bead args: %v", args)
	}
}

// TestShouldCreateReviewFixBead pins the open/closed routing logic that decides
// whether to sling the source bead directly or create a fresh dispatch bead.
// Closed, tombstoned, and absent source beads take the fresh-bead path; every
// other status (open, hooked, in_progress, etc.) uses the source bead directly.
func TestShouldCreateReviewFixBead(t *testing.T) {
	cases := []struct {
		name string
		bead *beads.Issue
		want bool
	}{
		{"nil (bead not found)", nil, true},
		{"closed (normal post-gt-done state)", &beads.Issue{Status: "closed"}, true},
		{"tombstone (work already completed)", &beads.Issue{Status: "tombstone"}, true},
		{"open (bead still active)", &beads.Issue{Status: "open"}, false},
		{"hooked (assigned to a polecat)", &beads.Issue{Status: "hooked"}, false},
		{"in_progress", &beads.Issue{Status: "in_progress"}, false},
		{"deferred", &beads.Issue{Status: "deferred"}, false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := shouldCreateReviewFixBead(c.bead); got != c.want {
				t.Errorf("shouldCreateReviewFixBead(%+v) = %v; want %v", c.bead, got, c.want)
			}
		})
	}
}

// TestPolecatNameFromAssignee pins the recovery of the spawned polecat's name
// from the source issue's assignee. gt sling has no JSON mode, so the dispatch
// reads the bead's `<rig>/polecats/<name>` assignee instead.
func TestPolecatNameFromAssignee(t *testing.T) {
	cases := []struct {
		name     string
		rig      string
		assignee string
		want     string
		wantErr  bool
	}{
		{"valid", "gastown", "gastown/polecats/furiosa", "furiosa", false},
		{"valid with whitespace", "gastown", "  gastown/polecats/max  ", "max", false},
		{"wrong rig", "gastown", "beads/polecats/furiosa", "", true},
		{"not a polecat", "gastown", "gastown/witness", "", true},
		{"empty name", "gastown", "gastown/polecats/", "", true},
		{"empty assignee", "gastown", "", "", true},
		{"trailing path segment", "gastown", "gastown/polecats/furiosa/extra", "", true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, err := polecatNameFromAssignee(c.rig, c.assignee)
			if c.wantErr {
				if err == nil {
					t.Errorf("polecatNameFromAssignee(%q, %q) = %q, nil; want error", c.rig, c.assignee, got)
				}
				return
			}
			if err != nil {
				t.Errorf("polecatNameFromAssignee(%q, %q) unexpected error: %v", c.rig, c.assignee, err)
			}
			if got != c.want {
				t.Errorf("polecatNameFromAssignee(%q, %q) = %q; want %q", c.rig, c.assignee, got, c.want)
			}
		})
	}
}

func argIndexOf(args []string, target string) int {
	for i, a := range args {
		if a == target {
			return i
		}
	}
	return -1
}

func valueAt(args []string, i int) string {
	if i < 0 || i >= len(args) {
		return "<out-of-range>"
	}
	return args[i]
}

// dispatchReviewFixState parsing side-checks: the field types are simple
// enough that we don't need a full integration test of parseDispatchMRFields
// (that path needs a real bead store). But we can confirm the struct
// renders refinery.ReviewThread imports correctly so the build doesn't
// silently drop the dependency.
func TestDispatchReviewFixState_StructShape(t *testing.T) {
	s := dispatchReviewFixState{
		PRNumber:       42,
		Branch:         "polecat/foo-gt-abc",
		SourceIssue:    "gt-abc",
		ReviewFixName:  "",
		ReviewLoopIter: 0,
	}
	if s.PRNumber != 42 || s.SourceIssue != "gt-abc" {
		t.Errorf("struct field round-trip failed: %+v", s)
	}
	// Compile-time reference to the refinery package so go vet doesn't
	// drop the import on a non-test build that excludes this file.
	var _ = refinery.ReviewThread{}
}

// TestReviewFixCapacityFull pins the pure full/free/disabled decision that
// gates a review-fix deferral. The gt-cza incident traced to `gt sling`
// silently no-op'ing on a full scheduler and the dispatch only logging "empty
// polecat name", so an operator misread a full scheduler as a load gate.
//   - gate disabled (Max <= 0): never full (gate off)
//   - slot free (Free > 0):     never full
//   - Free <= 0 with Max > 0:   full
func TestReviewFixCapacityFull(t *testing.T) {
	cases := []struct {
		name string
		snap polecatCapacitySnapshot
		want bool
	}{
		{"gate disabled", polecatCapacitySnapshot{Max: 0, Free: 0}, false},
		{"free slot", polecatCapacitySnapshot{Max: 6, Free: 2}, false},
		{"full", polecatCapacitySnapshot{Max: 6, Free: 0}, true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := reviewFixCapacityFull(c.snap); got != c.want {
				t.Errorf("reviewFixCapacityFull(%+v) = %v; want %v", c.snap, got, c.want)
			}
		})
	}
}

// TestReviewFixCapacityMessage pins the deferral log line. It must render the
// snapshot detail in both cases, but choose its remediation half from
// transience so the message never contradicts the exit code — the bug augment
// flagged on PR #124 was that routing through polecatCapacityAdmissionError's
// Error() always appended operator-remediation text even for transient
// peak-load, which the self-healing exit code (1) does not warrant.
func TestReviewFixCapacityMessage(t *testing.T) {
	t.Run("recovery-blocked yields actionable remedy", func(t *testing.T) {
		msg := reviewFixCapacityMessage(polecatCapacitySnapshot{Max: 6, RecoveryBlocked: 6, Free: 0})
		for _, frag := range []string{"max=6", "free=0", "recovery_blocked=6", "scheduler.max_polecats", "reap"} {
			if !strings.Contains(msg, frag) {
				t.Errorf("actionable capacity message missing %q (operator needs cause + remedy): %s", frag, msg)
			}
		}
	})
	t.Run("transient does not advise operator action", func(t *testing.T) {
		msg := reviewFixCapacityMessage(polecatCapacitySnapshot{Max: 6, Working: 6, Free: 0})
		if !strings.Contains(msg, "transient") {
			t.Errorf("transient capacity message must name the peak-load cause: %s", msg)
		}
		if !strings.Contains(msg, "max=6") {
			t.Errorf("transient capacity message must still render the snapshot detail: %s", msg)
		}
		// The self-healing exit code (1) means a transient deferral must not
		// advise the operator to reap or raise capacity.
		for _, banned := range []string{"reap", "scheduler.max_polecats"} {
			if strings.Contains(msg, banned) {
				t.Errorf("transient capacity message must not advise %q: %s", banned, msg)
			}
		}
	})
}

// TestReviewFixCapacityExitCode pins the transient-vs-actionable distinction
// for a full scheduler. A scheduler full only because of active (Working) or
// in-flight (Reservations) polecats is at transient peak load and self-heals,
// so it must retry quietly (exit 1) — escalating there would be a false alarm
// (gemini review feedback on PR #124). A scheduler held full by a
// RecoveryBlocked polecat will not free itself (the gt-cza case) and must
// escalate (exit 4).
func TestReviewFixCapacityExitCode(t *testing.T) {
	cases := []struct {
		name string
		snap polecatCapacitySnapshot
		want int
	}{
		{"all working is transient", polecatCapacitySnapshot{Max: 6, Working: 6}, 1},
		{"working plus reservations is transient", polecatCapacitySnapshot{Max: 6, Working: 5, Reservations: 1}, 1},
		{"recovery-blocked needs operator", polecatCapacitySnapshot{Max: 6, Working: 5, RecoveryBlocked: 1}, 4},
		{"all recovery-blocked needs operator", polecatCapacitySnapshot{Max: 6, RecoveryBlocked: 6}, 4},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := reviewFixCapacityExitCode(c.snap); got != c.want {
				t.Errorf("reviewFixCapacityExitCode(%+v) = %d; want %d", c.snap, got, c.want)
			}
		})
	}
}
