package cmd

import (
	"strings"
	"testing"

	"github.com/steveyegge/gastown/internal/refinery"
)

// TestExtractDescField pins the small parser used to read review_pr off the
// MR bead description. The MR-fields parser doesn't (yet) expose review_pr
// — it's added by the G11 no-merge+pr handoff — so the dispatch subcommand
// reads it directly. The parser must:
//   - find the first occurrence of `key:` (subsequent prose references to
//     the same key must NOT shadow the structured value)
//   - tolerate leading whitespace on the line (a bd description rendered
//     with indented prose blocks would otherwise miss the field)
//   - return empty string when the key is absent
func TestExtractDescField(t *testing.T) {
	cases := []struct {
		name string
		desc string
		key  string
		want string
	}{
		{"key not present", "branch: foo\n", "review_pr", ""},
		{"present at start", "review_pr: 42\nbranch: x\n", "review_pr", "42"},
		{"present mid-block", "branch: x\nreview_pr: 42\n", "review_pr", "42"},
		{"indented line tolerated", "  review_pr: 42\n", "review_pr", "42"},
		{"first wins over later prose mention", "review_pr: 42\nbranch: x\n\nlater: review_pr: 99 typo\n", "review_pr", "42"},
		{"empty value", "review_pr:\n", "review_pr", ""},
		{"value with surrounding whitespace", "review_pr:    42   \n", "review_pr", "42"},
		{"empty description", "", "review_pr", ""},
		{"key not present, prose mentions it", "Notes: see review_pr in the bead\n", "review_pr", ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := extractDescField(c.desc, c.key)
			if got != c.want {
				t.Errorf("extractDescField(%q, %q) = %q; want %q", c.desc, c.key, got, c.want)
			}
		})
	}
}

// TestBuildReviewFixMission pins the polecat-mission text generated by the
// dispatch subcommand. The mission must encode every behavioural invariant
// the formula's prose blob used to enforce, in numbered-step form so the
// LLM polecat can't blur the contract.
func TestBuildReviewFixMission(t *testing.T) {
	threadsJSON := `[{"id":"PRRT_xyz","author":"augmentcode","path":"a.go","line":42,"body":"fix"}]`
	mission := buildReviewFixMission(123, threadsJSON, "augmentcode")

	// Every invariant must be present in the rendered mission.
	requiredFragments := []struct {
		name string
		want string
	}{
		// G33: imperative branch-entry via the just-shipped subcommand.
		{"checkout-branch step 1", "gt polecat checkout-branch"},
		// G14: thread JSON enumerated verbatim, not paraphrased.
		{"threads JSON inline", threadsJSON},
		// G13: reply-AND-resolve, not reply-only.
		{"reply-and-resolve", "Resolve every thread"},
		{"resolve via gh api", "resolveReviewThread"},
		// G12b: author-agnostic.
		{"author-agnostic guidance", "regardless of opener"},
		// G36: gt done updates commit_sha (handles bead refresh).
		{"gt done completion", "gt done"},
		// PR number rendered.
		{"PR number rendered", "PR #123"},
		// Reviewer name rendered when supplied.
		{"reviewer name rendered", "augmentcode"},
	}
	for _, rf := range requiredFragments {
		t.Run(rf.name, func(t *testing.T) {
			if !strings.Contains(mission, rf.want) {
				t.Errorf("mission missing %q: got %q", rf.want, mission)
			}
		})
	}

	// Ensure mission text is imperative-steps-first (numbered list) rather
	// than narrative — the original formula prose was the failure mode this
	// fix exists to close.
	for _, step := range []string{"1.", "2.", "3.", "4.", "5.", "6.", "7."} {
		if !strings.Contains(mission, step) {
			t.Errorf("mission missing step %q (must be numbered for LLM clarity): %s", step, mission)
		}
	}
}

// Empty reviewer name shouldn't render an empty parenthetical
// — the mission falls back to "the configured pr_reviewer" wording.
func TestBuildReviewFixMission_EmptyReviewer_RendersFallback(t *testing.T) {
	mission := buildReviewFixMission(7, "[]", "")
	if strings.Contains(mission, "wake (the configured pr_reviewer)") {
		t.Errorf("empty reviewer must not produce empty parenthetical, got: %s", mission)
	}
	if !strings.Contains(mission, "the configured pr_reviewer") {
		t.Errorf("empty reviewer must fall back to generic 'the configured pr_reviewer' phrasing, got: %s", mission)
	}
}

// dispatchReviewFixState parsing side-checks: the field types are simple
// enough that we don't need a full integration test of parseDispatchMRFields
// (that path needs a real bead store). But we can confirm the struct
// renders refinery.ReviewThread imports correctly so the build doesn't
// silently drop the dependency.
func TestDispatchReviewFixState_StructShape(t *testing.T) {
	s := dispatchReviewFixState{
		PRNumber:       42,
		Branch:         "polecat/foo-gt-abc",
		SourceIssue:    "gt-abc",
		ReviewFixName:  "",
		ReviewLoopIter: 0,
	}
	if s.PRNumber != 42 || s.SourceIssue != "gt-abc" {
		t.Errorf("struct field round-trip failed: %+v", s)
	}
	// Compile-time reference to the refinery package so go vet doesn't
	// drop the import on a non-test build that excludes this file.
	var _ = refinery.ReviewThread{}
}
